' Gambas module file

Private OpcodeConversionMap As Collection = [
  "J": Instruction.OP_J,
  "JEQ": Instruction.OP_JEQ,
  "JNE": Instruction.OP_JNE,
  "JLT": Instruction.OP_JLT,
  "JGE": Instruction.OP_JGE,
  "JGTU": Instruction.OP_JGTU,
  "JLEU": Instruction.OP_JLEU,
  "JLE": Instruction.OP_JLE,
  "JGT": Instruction.OP_JGT,
  "JGEU": Instruction.OP_JGEU,
  "JLTU": Instruction.OP_JLTU,
  "JO": Instruction.OP_JO,
  "JNO": Instruction.OP_JNO,
  "JS": Instruction.OP_JS,
  "JNS": Instruction.OP_JNS,
  
  "TEST": Instruction.OP_TEST,
  "TESTN": Instruction.OP_TESTN,
  "AND": Instruction.OP_AND,
  "ANDN": Instruction.OP_ANDN,
  "OR": Instruction.OP_OR,
  "ORN": Instruction.OP_ORN,
  "XOR": Instruction.OP_XOR,
  "XNOR": Instruction.OP_XNOR,
  "STB": Instruction.OP_STB,
  "STH": Instruction.OP_STH,
  "STW": Instruction.OP_STW,
  "LDB": Instruction.OP_LDB,
  "LDH": Instruction.OP_LDH,
  "LDW": Instruction.OP_LDW,
  "ADD": Instruction.OP_SHADD,
  "SH1ADD": Instruction.OP_SHADD,
  "SH2ADD": Instruction.OP_SHADD,
  "SH3ADD": Instruction.OP_SHADD,
  "ADC": Instruction.OP_ADC,
  "SBC": Instruction.OP_SBC,
  "SUB": Instruction.OP_SUB,
  "ZEXTB": Instruction.OP_ZEXTB,
  "ZEXTH": Instruction.OP_ZEXTH,
  "SEXTB": Instruction.OP_SEXTB,
  "SEXTH": Instruction.OP_SEXTH,
  
  "CMP": Instruction.OP_CMP,
  "MOV": Instruction.OP_MOV,
  "MOVEQ": Instruction.OP_MOVEQ,
  "MOVNE": Instruction.OP_MOVNE,
  "MOVLT": Instruction.OP_MOVLT,
  "MOVGE": Instruction.OP_MOVGE,
  "MOVLE": Instruction.OP_MOVLE,
  "MOVGT": Instruction.OP_MOVGT,
  "MOVO": Instruction.OP_MOVO,
  "MOVNO": Instruction.OP_MOVNO,
  "MOVS": Instruction.OP_MOVS,
  "MOVNS": Instruction.OP_MOVNS,
  "MOVGTU": Instruction.OP_MOVGTU,
  "MOVLEU": Instruction.OP_MOVLEU,
  "MOVGEU": Instruction.OP_MOVGEU,
  "MOVLTU": Instruction.OP_MOVLTU,
  
  "TEST:I": Instruction.OP_TEST_I,
  "AND:I": Instruction.OP_AND_I,
  "OR:I": Instruction.OP_OR_I,
  "XOR:I": Instruction.OP_XOR_I,
  "STW:I": Instruction.OP_STW_I,
  "LDW:I": Instruction.OP_LDW_I,
  "ADD:I": Instruction.OP_ADD_I,
  "SH1": Instruction.OP_SH,
  "SH2": Instruction.OP_SH,
  "SH3": Instruction.OP_SH,
  "ROR": Instruction.OP_ROR,
  "ROL": Instruction.OP_ROL,
  "RCL": Instruction.OP_RCL,
  "SRL": Instruction.OP_SRL,
  "SRA": Instruction.OP_SRA,
  "CMP:I": Instruction.OP_CMP_I,
  "MOVEQ:I": Instruction.OP_MOVEQ_I,
  "MOVNE:I": Instruction.OP_MOVNE_I,
  
  "ENTER": Instruction.OP_ENTER,
  "ENTERL": Instruction.OP_ENTERL,
  "EXIT": Instruction.OP_EXIT,
  "EXITL": Instruction.OP_EXITL,
  "LINK": Instruction.OP_LINK,
  "RET": Instruction.OP_RET,
  
  "LDW:P": Instruction.OP_LDW_P,
  "MOV:RP": Instruction.OP_MOV_RP,
  "MOV:RL": Instruction.OP_MOV_RL,
  "STW:P": Instruction.OP_STW_P,
  "MOV:PR": Instruction.OP_MOV_PR,
  "MOV:LR": Instruction.OP_MOV_LR,
  "LDW:PI": Instruction.OP_LDW_PI,
  "STW:PI": Instruction.OP_STW_PI,
]

Public Function Parse(StatementList As Statement[]) As Program
  
  Dim vProgram As Program = New Program
  Dim tDataBytes As DataByte[]
  
  For Each iStatement As Statement In StatementList
    Dim vCommand As Token = iStatement.Tokens[0]
    Select Case vCommand.Type
      Case Token.TYPE_DIRECTIVE
        For i As Integer = 1 To iStatement.Tokens.Length - 1 Step 2
          Dim vArg As Token = iStatement.Tokens[i]
          
          Select Case vArg.Type
            Case Token.TYPE_STRING
              For j As Integer = 0 To vArg.Word.Length - 1
                Dim unicode As Integer = String.Code(vArg.Word, j)
                tDataBytes = GetDataBytes(vCommand.Word, unicode)
                
                For Each iDataByte As DataByte In tDataBytes
                  vProgram.Data.Add(iDataByte)
                Next
              Next
            Case Token.TYPE_NUMERIC
              tDataBytes = GetDataBytes(vCommand.Word, vArg.Word)
              For Each iDataByte As DataByte In tDataBytes
                vProgram.Data.Add(iDataByte)
              Next
            Case Else 
              Error.Raise("This shouldn't happen!")
          End Select
        Next
      Case Token.TYPE_OPCODE
        Select Case vCommand.Word
            Case "J", "JEQ", "JNE", "JLT", "JGE", "JLTU", "JGEU", "JLE", "JGT", "JLEU", "JGTU", "JO", "JNO", "JS", "JNS"
            Case "LDW", "STW"
            Case "LDB", "LDH", "STB", "STH"
            Case "MOV"
              vProgram.Instructions.Add(MovOp(iStatement))
            Case "CMP", "AND", "OR", "XOR", "ADD", "ROL", "ROR", "TEST", "MOVEQ", "MOVNE"
              vProgram.Instructions.Add(OpSourceRegImm(iStatement))
            Case "ANDN", "ORN", "XNOR", "SH1ADD", "SH2ADD", "SH3ADD", "ADC", "SBC" "SUB", "ZEXTB", "ZEXTH", "SEXTB", "SEXTH", "TESTN", "MOVLT", "MOVLE", "MOVGT", "MOVGE", "MOVLTU", "MOVLEU", "MOVGTU", "MOVGEU", "MOVS", "MOVNS", "MOVO", "MOVNO"
              vProgram.Instructions.Add(OpSourceReg(iStatement))
            Case "SH1", "SH2", "SH3", "SRA", "SRL"
              vProgram.Instructions.Add(OpDestOnly(iStatement))
            Case "ENTER", "ENTERL", "EXIT", "EXITL"
              vProgram.Instructions.Add(EnterExit(iStatement))
            Case "NOP", "RET", "LINK"
              vProgram.Instructions.Add(NoArguments(iStatement))
            Case Else 
              Error.Raise("This shouldn't happen!")
        End Select
      Case Else 
        Error.Raise("This shouldn't happen!")
    End Select
  Next
End 

Private Function MovOp(StatementA As Statement) As Instruction
  
  Dim Valid As Boolean = False
  
  Dim Dest As Argument
  Dim Source As Argument
  
  Dim Tokens As Token[] = StatementA.Tokens
  
  If Tokens.Length <> 4 Or If Tokens[1].Type <> Token.TYPE_REGISTER Or If Tokens[2].Word <> "," Then Error.Raise("Invalid syntax for " & Tokens[0].Word)
  
  Dim DestIndex As Integer = Utility.StrInList(Tokens[1].Word, Keywords.REGISTERS)
  Dim SourceIndex As Integer
  
  If DestIndex = 20 Then 
    Dest = New ArgLinkRegister
  Else If DestIndex >= 16 Then 
    Dest = New ArgPtrRegister(DestIndex)
  Else 
    Valid = True
    Dest = New ArgRegister(DestIndex)
  Endif
  
  Select Case Tokens[3].Type
    Case Token.TYPE_REGISTER
      SourceIndex = Utility.StrInList(Tokens[3].Word, Keywords.REGISTERS)
      If SourceIndex = 20 Then 
        Source = New ArgLinkRegister
      Else If SourceIndex >= 16 Then 
        Source = New ArgPtrRegister(SourceIndex)
      Else 
        Valid = True
        Source = New ArgRegister(SourceIndex)
      Endif
    Case Token.TYPE_NUMERIC
      Source = New ArgNumeric(Tokens[3].Word)
    Case Else 
      Error.Raise("Invalid syntax for " & Tokens[0].Word)
  End Select
  
  If Not Valid Then Error.Raise("Invalid syntax for " & Tokens[0].Word)
  
  Return Instruction.Build(StatementA.Address, Tokens[0].Word, Dest, Source)
  
End


Private Function OpSourceRegImm(StatementA As Statement) As Instruction
  
  Dim Dest As Argument
  Dim Source As Argument
  
  Dim Tokens As Token[] = StatementA.Tokens
  
  If Tokens.Length <> 4 Or If Tokens[1].Type <> Token.TYPE_REGISTER Or If Tokens[2].Word <> "," Then Error.Raise("Invalid syntax for " & Tokens[0].Word)
  
  Try Dest = New ArgRegister(Utility.StrInList(Tokens[1].Word, Keywords.REGISTERS))
  
  Select Case Tokens[3].Type
    Case Token.TYPE_REGISTER
      Try Source = New ArgRegister(Utility.StrInList(Tokens[3].Word, Keywords.REGISTERS))
    Case Token.TYPE_NUMERIC
      Source = New ArgNumeric(Tokens[3].Word)
    Case Else 
      Error.Raise("Invalid syntax for " & Tokens[0].Word)
  End Select
  
  If Error Then Error.Raise(Tokens[0].Word & " cannot take special registers as arguments")
  
  Return Instruction.Build(StatementA.Address, Tokens[0].Word, Dest, Source)
  
End
  
Private Function OpSourceReg(StatementA As Statement) As Instruction
  
  Dim Dest As Argument
  Dim Source As Argument
  
  Dim Tokens As Token[] = StatementA.Tokens
  
  If Tokens.Length <> 4 Or If Tokens[1].Type <> Token.TYPE_REGISTER Or If Tokens[2].Word <> "," Or If Tokens[3].Type <> Token.TYPE_REGISTER Then Error.Raise("Invalid syntax for " & Tokens[0].Word)
  
  Try Dest = New ArgRegister(Utility.StrInList(Tokens[1].Word, Keywords.REGISTERS))
  Try Source = New ArgRegister(Utility.StrInList(Tokens[3].Word, Keywords.REGISTERS))
  
  If Error Then Error.Raise(Tokens[0].Word & " cannot take special registers as arguments")
  
  Return Instruction.Build(StatementA.Address, Tokens[0].Word, Dest, Source)
  
End

Private Function OpDestOnly(StatementA As Statement) As Instruction
  
  Dim Tokens As Token[] = StatementA.Tokens
  
  If Tokens.Length <> 2 Or If Tokens[1].Type <> Token.TYPE_REGISTER Then Error.Raise("Invalid syntax for " & Tokens[0].Word)
  
  Dim Register As Argument
  
  Try Register = New ArgRegister(Utility.StrInList(Tokens[1].Word, Keywords.REGISTERS))
  
  If Error Then Error.Raise(Tokens[0].Word & " cannot take a special register as its argument")
  
  Return Instruction.Build(StatementA.Address, Tokens[0].Word, Register)
  
End

  
Private Function EnterExit(StatementA As Statement) As Instruction
  
  If StatementA.Tokens[1].Word <> "[" Or If StatementA.Tokens[3].Word <> "-" Or If StatementA.Tokens[5].Word <> "]" Then Error.Raise("Invalid syntax for " & StatementA.Tokens[0].Word)
  If StatementA.Tokens[2].Type <> Token.TYPE_REGISTER Or If StatementA.Tokens[4].Type <> Token.TYPE_REGISTER Then Error.Raise("Invalid syntax for " & StatementA.Tokens[0].Word)
  
  Dim ExtraSpace As Integer
  If StatementA.Tokens.Length = 6 Then 
    ExtraSpace = 0
  Else If StatementA.Tokens.Length = 8 Then 
    If StatementA.Tokens[6].word <> "," Or If StatementA.Tokens[7].Type <> Token.TYPE_NUMERIC Then Error.Raise("Invalid syntax for " & StatementA.Tokens[0].Word)
    
    ExtraSpace = StatementA.Tokens[7].Word
  Else 
    Error.Raise("Invalid syntax for " & StatementA.Tokens[0].Word)
  Endif
  
  Dim RegIndex1 As Integer = Utility.StrInList(StatementA.Tokens[2].Word, Keywords.REGISTERS)
  Dim RegIndex2 As Integer = Utility.StrInList(StatementA.Tokens[4].Word, Keywords.REGISTERS)
  
  If RegIndex1 > 15 Or If RegIndex2 > 15 Then Error.Raise("Register list cannot include SP, AP, BP, CP, or LR")
  If RegIndex1 <> 0 Then Error.Raise("Register list must start from R0")
  If RegIndex2 % 2 <> 1 Then Error.Raise("Register list must end with an odd-indexed register")
  
  Dim RegCount As Integer = RegIndex2 + 1
  Dim Arg1 As Argument = New ArgRegList(RegCount)
  
  Dim TotalSpace As Integer = ExtraSpace + RegCount * 4
  Dim Arg2 As Argument = New ArgNumeric(TotalSpace)
  
  Return Instruction.Build(StatementA.Address, StatementA.Tokens[0].Word, Arg1, Arg2)
  
End

  
Private Function NoArguments(StatementA As Statement) As Instruction
  
  If StatementA.Tokens.Length <> 1 Then Error.Raise("Too many arguments for " & StatementA.Tokens[0].Word)
  
  Return Instruction.Build(StatementA.Address, StatementA.Tokens[0].Word)
  
End

  
Private Function GetDataBytes(DeclType As String, Value As Integer) As DataByte[]
  'TO-DO: Get dem data bayts!
End 
